<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <UserSecretsId>5461598b-3e78-461e-b0e9-50aaa7fbc56f</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Views\NewFolder1\**" />
    <Content Remove="Views\NewFolder1\**" />
    <EmbeddedResource Remove="Views\NewFolder1\**" />
    <None Remove="Views\NewFolder1\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="5.0.2" />
    <PackageReference Include="System.Data.SqlClient" Version="4.8.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WinetrackerGen.ApplicationCore\WinetrackerGen.ApplicationCore.csproj" />
    <ProjectReference Include="..\WinetrackerGen.Infraestructure\WinetrackerGen.Infraestructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Antlr3.Runtime">
      <HintPath>..\winetrackerGenNHibernate\AppLib\Antlr3.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="Castle.DynamicProxy2">
      <HintPath>..\winetrackerGenNHibernate\AppLib\Castle.DynamicProxy2.dll</HintPath>
    </Reference>
    <Reference Include="Iesi.Collections">
      <HintPath>..\winetrackerGenNHibernate\AppLib\Iesi.Collections.dll</HintPath>
    </Reference>
    <Reference Include="jose-jwt">
      <HintPath>..\winetrackerGenNHibernate\AppLib\jose-jwt.dll</HintPath>
    </Reference>
    <Reference Include="LinFu.DynamicProxy">
      <HintPath>..\winetrackerGenNHibernate\AppLib\LinFu.DynamicProxy.dll</HintPath>
    </Reference>
    <Reference Include="log4net">
      <HintPath>..\winetrackerGenNHibernate\AppLib\log4net.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>..\winetrackerGenNHibernate\AppLib\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="NHibernate">
      <HintPath>..\winetrackerGenNHibernate\AppLib\NHibernate.dll</HintPath>
    </Reference>
    <Reference Include="NHibernate.ByteCode.Castle">
      <HintPath>..\winetrackerGenNHibernate\AppLib\NHibernate.ByteCode.Castle.dll</HintPath>
    </Reference>
    <Reference Include="NHibernate.ByteCode.LinFu">
      <HintPath>..\winetrackerGenNHibernate\AppLib\NHibernate.ByteCode.LinFu.dll</HintPath>
    </Reference>
    <Reference Include="nunit.core">
      <HintPath>..\winetrackerGenNHibernate\AppLib\nunit.core.dll</HintPath>
    </Reference>
    <Reference Include="nunit.framework">
      <HintPath>..\winetrackerGenNHibernate\AppLib\nunit.framework.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\NewFolder\" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="Views\Usuario\Cesta.cshtml">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Update="Views\Usuario\misVentas.cshtml">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

</Project>
